In [1]:
import numpy as np
a = np.array([1,2,3])
b = np.array((1,2,3))
print(a)
print(b)

[1 2 3]
[1 2 3]


In [2]:
b[1] = 4

In [3]:
b

array([1, 4, 3])

In [4]:
c = np.array([[1,2,3],[4,5,6]])
print(c)

[[1 2 3]
 [4 5 6]]


In [5]:
c[0]

array([1, 2, 3])

In [6]:
c[1]

array([4, 5, 6])

In [9]:
a = np.zeros((3,4))
# np.zeros((row,column))
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [12]:
a = np.arange(10,25,5)

In [13]:
print(a)

[10 15 20]


In [14]:
# np.arange(startnum, endnumber, interval)
# startnum till endnum-interval
a = np.arange(10,20,2)
print(a)

[10 12 14 16 18]


In [18]:
# np.linspace(startnum, endnum, numberofpoints)
b = np.linspace(5,6,10)
print(b)

[5.         5.11111111 5.22222222 5.33333333 5.44444444 5.55555556
 5.66666667 5.77777778 5.88888889 6.        ]


In [21]:
import numpy as np
# np.full((row,column),numbertofill)
c = np.full((3,4),5)
print(c)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [22]:
import numpy as np
d = np.random.random((3,4))
print(d)

[[0.33628535 0.68235432 0.87266484 0.55721765]
 [0.79222606 0.80642572 0.5312543  0.95939865]
 [0.23245661 0.73719377 0.67079854 0.27065873]]


In [32]:
a = np.array([[1,2,3],[4,5,6]])

In [33]:
print(a)
# np.array.shape returns tuple (row,column)
print(a.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [36]:
a.shape = (3,2)
print(a.shape[0])
print(a.shape[1])
# returns the number of dimensions of the array
print(a.ndim)
print(a)

3
2
2
[[1 2]
 [3 4]
 [5 6]]


In [37]:
# np.arange(numberofpointsneeded)
# will place the numbers between 0 till that number
a = np.arange(24)

In [38]:
a.size

24

In [39]:
a.dtype

dtype('int32')

In [40]:
b = np.linspace(5,7,11)
print(b)
b.dtype

[5.  5.2 5.4 5.6 5.8 6.  6.2 6.4 6.6 6.8 7. ]


dtype('float64')

In [41]:
a = np.array([5,10])
np.sum(a)

15

In [47]:
b = [2,3]
print(np.sum([a,b]))
print(np.subtract(a,b))

20
[3 7]


In [54]:
print(np.sum([a,b], axis=0))
print(np.sum([a,b], axis=1))
print(np.sum([[0,1],[0,5]], axis=1))
print(np.sum([[0,1],[0,5]], axis=0))

[ 7 13]
[15  5]
[1 5]
[0 6]


In [61]:
print(a,b)
print(np.divide(a,b))
print(np.multiply(a,b))

[ 5 10] [2, 3]
[2.5        3.33333333]
[10 30]


In [64]:
print(np.exp(a))
print(np.sqrt(a))
print(np.sin(a))
print(np.cos(a))
print(np.log(a))

[  148.4131591  22026.46579481]
[2.23606798 3.16227766]
[-0.95892427 -0.54402111]
[ 0.28366219 -0.83907153]
[1.60943791 2.30258509]


In [67]:
# comparisons
a = [1,2,3]
b = [3,2,5]
print(np.equal(a,b))
print(np.array_equal(a,b))

[False  True False]
False


In [71]:
# aggregate functions
a = np.array([1,2,3])
print(np.sum(a))
print(np.min(a))
print(np.max(a))
print(np.mean(a))
print(np.std(a))
print(np.median(a))
print(np.corrcoef(a))

6
1
3
2.0
0.816496580927726
2.0
1.0


In [78]:
# array broadcasting
a = np.array([[1,2,3],[4,5,6]])
b = np.array([3,4,5])
print(a)
print(b)
print(np.sum([a,b]))
print(np.subtract(a,b))

[[1 2 3]
 [4 5 6]]
[3 4 5]
[[ 4  6  8]
 [ 7  9 11]]
[[-2 -2 -2]
 [ 1  1  1]]


In [86]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[3,4,5],[5,6,7]])
print(a)
print(b)
print(np.concatenate([a,b], axis = 0))
print(np.concatenate([a,b], axis = 1))

[[1 2 3]
 [4 5 6]]
[[3 4 5]
 [5 6 7]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]
[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [87]:
print(np.stack((a,b), axis=0))
print(np.stack((a,b), axis=1))

[[[1 2 3]
  [4 5 6]]

 [[3 4 5]
  [5 6 7]]]
[[[1 2 3]
  [3 4 5]]

 [[4 5 6]
  [5 6 7]]]


In [89]:
print(np.hstack((a,b)))
print(np.vstack((a,b)))

[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]
[[1 2 3]
 [4 5 6]
 [3 4 5]
 [5 6 7]]


In [93]:
print(np.column_stack((a,b)))

[[1 2 3 3 4 5]
 [4 5 6 5 6 7]]


In [125]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(a)
# np.split(array, index, axis) --> axis = 0 or 1, index is the number of sub arrays u want, if we have 2 subarrays originally
# we can take 1 or 2, if we have 3 sub arrays we can take 1,3 , if we have 4 subarrays we can take 1,2,4 so on
print(np.split(a,2,0))
print(np.split(a,[1,2],0))
print(np.split(a,[1,2],1))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]])]
[array([[ 1],
       [ 4],
       [ 7],
       [10]]), array([[ 2],
       [ 5],
       [ 8],
       [11]]), array([[ 3],
       [ 6],
       [ 9],
       [12]])]


In [ ]:
# numpy arrays are faster, stores less memory and are more convenient to use than python lists
# the reasons for this is, that the elements in numpy array are stored contagiously and the name points to first location
# while the elements in the list store the addresses of the data stored else where in memory
# so unlike lists, we don't use extra space to store addresses so less memory and faster retrieval
# convenient because we have many more methods we can operate on numpy arrays than lists